export const TEXT_CHANGE = 'textChange'
export const SUBMIT_TEXT = 'submitText'
export const PLAY = 'play'
export const INCREMENT = 'increment'
export const DECREMENT = 'decrement'
export const PAUSE = 'pause'
export const STOP = 'stop'
export const SEEK_PLACE = 'seekPlace'
